### ISSUE TITLE
Images are missing from custom html report for selenium project

### ISSUE THREAD

**Issue by SUDARSHANCHAUDHARI** [AirtestProject/airtest-selenium#1]
Hello All
I am using the following format to run .air file from CLI for my selenium project.

@echo off

"C:\AirtestIDE\AirtestIDE" runner "(AIR FILE PATH)"  --log "(PATH FOR FOLDER)"

C:\AirtestIDE\AirtestIDE reporter "AIR FILE PATH"  --log_root "PATH FOR FOLDER"  --outfile "PATH FOR FOLDER\log.html"  --static_root C:\AirtestIDE\airtest\report  --lang en 

@pause 

thing is all images appear when I run from Airetest IDE and missing when I used CLI
![image](https://user-images.githubusercontent.com/25879455/42856737-c4dfa7e2-8a70-11e8-8fe6-02ac8290f059.png)

**Comment by SUDARSHANCHAUDHARI** [comment]
found one link in Jenkins console output

C:\AirtestIDE\selenium\webdriver\remote\webdriver.py:1009: UserWarning: name used for saved screenshot does not match file type. It should end with a `.png` extension
  "type. It should end with a `.png` extension", UserWarning)

**Comment by zzldjkzxf** [comment]
@SUDARSHANCHAUDHARI  maybe you can add "--plugin airtest_selenium.report" after your reporter command.

**Comment by zzldjkzxf** [comment]
@SUDARSHANCHAUDHARI  and you should command "pip install airtest-selenium" first
.

**Comment by SUDARSHANCHAUDHARI** [comment]
Thank you very much for the help @adoli and @zzldjkzxf .
Closing this issue
